name: weather
version: "1.0.0"
config-version: 2
profile: weather

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  weather:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
